[2022-03-31 22:21:41] [WARNING]: 恢复会话失败: exchange_emp failed: 16 , 尝试使用正常流程登录. 
[2022-03-31 22:21:43] [WARNING]: 账号已开启设备锁，请选择验证方式: 
[2022-03-31 22:21:43] [WARNING]: 1. 向手机 132******33 发送短信验证码 
[2022-03-31 22:21:43] [WARNING]: 2. 使用手机QQ扫码验证. 
[2022-03-31 22:21:43] [WARNING]: 请输入(1 - 2) (将在10秒后自动选择2)： 
[2022-03-31 22:21:45] [WARNING]: 请输入短信验证码： (Enter 提交) 
[2022-03-31 22:35:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-31 22:35:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-31 22:36:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-31 22:36:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-31 22:36:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:64818->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 3 次重试 
[2022-03-31 22:36:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:64821->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 1 次重试 
[2022-03-31 22:36:54] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":39,"PacketSent":27,"PacketLost":0,"MessageReceived":3,"MessageSent":2,"LastMessageTime":1648737391,"DisconnectTimes":0,"LostTimes":0}},"time":1648737393}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:36:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:36:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:36:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:36:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:01] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":822612889,"message":"/market Mana 魔匠魔晶石柒型","message_id":1446816856,"message_seq":578,"message_type":"group","post_type":"message","raw_message":"/market Mana 魔匠魔晶石柒型","self_id":3102833903,"sender":{"age":0,"area":"","card":"","level":"","nickname":"普通人阿文","role":"owner","sex":"unknown","title":"","user_id":1270672343},"sub_type":"normal","time":1648737406,"user_id":1270672343}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:06] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":45,"PacketSent":31,"PacketLost":0,"MessageReceived":4,"MessageSent":3,"LastMessageTime":1648737407,"DisconnectTimes":0,"LostTimes":0}},"time":1648737414}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:37:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:19] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":45,"PacketSent":31,"PacketLost":0,"MessageReceived":4,"MessageSent":3,"LastMessageTime":1648737407,"DisconnectTimes":0,"LostTimes":0}},"time":1648737426}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:37:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:32] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":46,"PacketSent":32,"PacketLost":0,"MessageReceived":4,"MessageSent":3,"LastMessageTime":1648737407,"DisconnectTimes":0,"LostTimes":0}},"time":1648737439}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:37:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:37:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:44] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":46,"PacketSent":32,"PacketLost":0,"MessageReceived":4,"MessageSent":3,"LastMessageTime":1648737407,"DisconnectTimes":0,"LostTimes":0}},"time":1648737452}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:37:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:37:51] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":822612889,"message":"/luck","message_id":557554894,"message_seq":579,"message_type":"group","post_type":"message","raw_message":"/luck","self_id":3102833903,"sender":{"age":0,"area":"","card":"","level":"","nickname":"普通人阿文","role":"owner","sex":"unknown","title":"","user_id":1270672343},"sub_type":"normal","time":1648737458,"user_id":1270672343}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:37:57] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":48,"PacketSent":33,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737464}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:37:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:38:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:38:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:38:10] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":48,"PacketSent":33,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737477}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:38:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:38:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:38:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:38:22] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":49,"PacketSent":34,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737490}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:38:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:38:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:38:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:38:35] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":49,"PacketSent":34,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737502}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:38:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:38:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:38:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:38:48] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":49,"PacketSent":34,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737515}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:38:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:38:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:38:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:39:01] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":51,"PacketSent":36,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737528}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:39:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:39:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:39:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:39:13] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":51,"PacketSent":36,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737541}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:39:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:39:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:39:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:39:26] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":52,"PacketSent":37,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737553}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:39:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:39:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:39:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:39:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":52,"PacketSent":37,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737566}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:39:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:39:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:39:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:39:51] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":53,"PacketSent":38,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737579}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:39:53] [FATAL]: 打开数据库失败: open backend error: open leveldb error: The process cannot access the file because it is being used by another process. 
[2022-03-31 22:40:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:40:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:40:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:40:20] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":54,"PacketSent":39,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737608}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:40:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:40:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:40:28] [FATAL]: 打开数据库失败: open backend error: open leveldb error: The process cannot access the file because it is being used by another process. 
[2022-03-31 22:41:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:41:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:41:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:41:15] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":55,"PacketSent":40,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737663}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:41:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:41:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-31 22:41:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-31 22:41:28] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":56,"PacketSent":41,"PacketLost":0,"MessageReceived":5,"MessageSent":3,"LastMessageTime":1648737458,"DisconnectTimes":0,"LostTimes":0}},"time":1648737675}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-31 22:41:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-31 22:41:32] [FATAL]: 打开数据库失败: open backend error: open leveldb error: The process cannot access the file because it is being used by another process. 
